apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: online-store-prometheus-rules
  namespace: rp3
  labels:
    app: online-store
    job: online-store
    release: prometheus
    team: sre
spec:
  groups:
  - name: online-store-SLOs-http_request_duration_seconds
    rules:
    - alert: OnlineStore_LatencyBudgetBurn
      annotations:
        message: 'High requests latency budget burn for job=online-store,latency=1 (current value: {{ $value }})'
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1h{job="online-store",latency="1"} > (14.4*(1-0.800000))
          and
          latencytarget:http_request_duration_seconds:rate5m{job="online-store",latency="1"} > (14.4*(1-0.800000))
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate6h{job="online-store",latency="1"} > (6*(1-0.800000))
          and
          latencytarget:http_request_duration_seconds:rate30m{job="online-store",latency="1"} > (6*(1-0.800000))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
        severity: page
    - alert: OnlineStore_LatencyBudgetBurn
      annotations:
        message: 'High requests latency budget burn for job=online-store,latency=1 (current value: {{ $value }})'
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1d{job="online-store",latency="1"} > (3*(1-0.800000))
          and
          latencytarget:http_request_duration_seconds:rate2h{job="online-store",latency="1"} > (3*(1-0.800000))
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate3d{job="online-store",latency="1"} > (1.000000)
          and
          latencytarget:http_request_duration_seconds:rate6h{job="online-store",latency="1"} > (1.000000)
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
        severity: ticket
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[5m]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[5m]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
        severity: page
      record: latencytarget:http_request_duration_seconds:rate5m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[30m]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[30m]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate30m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[1h]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[1h]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate1h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[2h]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[2h]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate2h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[6h]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[6h]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate6h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[1d]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[1d]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate1d
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="online-store",le="1",code!~"5.."}[3d]))
          /
          sum(rate(http_request_duration_seconds_count{job="online-store"}[3d]))
        )
      labels:
        app: online-store
        job: online-store
        release: prometheus
        latency: "1"
      record: latencytarget:http_request_duration_seconds:rate3d

  - name: online-store-SLOs-http_requests_total
    rules:
    - alert: OnlineStore_ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=online-store (current value: {{ $value }})'
      expr: |
        sum(onlineStore_http_server_requests_seconds_count:burnrate5m{job="online-store"}) > (14.40 * (1-0.95000))
        and
        sum(onlineStore_http_server_requests_seconds_count:burnrate1h{job="online-store"}) > (14.40 * (1-0.95000))
      for: 2m
      labels:
        app: online-store
        job: online-store
        release: prometheus
        severity: page
    - alert: OnlineStore_ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=online-store (current value: {{ $value }})'
      expr: |
        sum(onlineStore_http_server_requests_seconds_count:burnrate30m{job="online-store"}) > (6.00 * (1-0.95000))
        and
        sum(onlineStore_http_server_requests_seconds_count:burnrate6h{job="online-store"}) > (6.00 * (1-0.95000))
      for: 15m
      labels:
        app: online-store
        job: online-store
        release: prometheus
        severity: page
    - alert: OnlineStore_ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=online-store (current value: {{ $value }})'
      expr: |
        sum(onlineStore_http_server_requests_seconds_count:burnrate2h{job="online-store"}) > (3.00 * (1-0.95000))
        and
        sum(onlineStore_http_server_requests_seconds_count:burnrate1d{job="online-store"}) > (3.00 * (1-0.95000))
      for: 1h
      labels:
        app: online-store
        job: online-store
        release: prometheus
        severity: ticket
    - alert: OnlineStore_ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=online-store (current value: {{ $value }})'
      expr: |
        sum(onlineStore_http_server_requests_seconds_count:burnrate6h{job="online-store"}) > (1.00 * (1-0.95000))
        and
        sum(onlineStore_http_server_requests_seconds_count:burnrate3d{job="online-store"}) > (1.00 * (1-0.95000))
      for: 3h
      labels:
        app: online-store
        job: online-store
        release: prometheus
        severity: ticket
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[1d]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[1d]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate1d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[1h]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[1h]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate1h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[2h]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[2h]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate2h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[30m]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[30m]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate30m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[3d]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[3d]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate3d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[5m]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate5m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="online-store",status=~"5.."}[6h]))
        /
        sum(rate(http_server_requests_seconds_count{job="online-store"}[6h]))
      labels:
        app: online-store
        job: online-store
        release: prometheus
      record: onlineStore_http_server_requests_seconds_count:burnrate6h