apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-store
  namespace: rp3
  labels:
    app: one
    release: prometheus
    team: sre
spec:  
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s
  namespaceSelector:
    matchNames: 
    - rp3
  selector:
    matchLabels:
      app: one