apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: online-store
  namespace: rp3
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /online-store-rp3/?(.*)
        backend:
          serviceName: online-store
          servicePort: 8080
