apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-store
  namespace: rp3
  labels:
    app: online-store
    release: prometheus
    team: sre
spec:
  selector:
    matchLabels:
      app: online-store
  namespaceSelector:
    matchNames: 
    - rp3
  endpoints:
  - port: http
    path: p1/actuator/prometheus
    interval: 10s