apiVersion: v1
kind: Service
metadata:
  name: online-store
  namespace: rp3
  labels:
    app: online-store
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: online-store
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP