apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store-production
  namespace: rp3 
  labels: 
    app: one
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: one
      track: stable
  template:
    metadata:
      labels:
        app: one
        track: stable
    spec:
      volumes:
        - name: config
          configMap:
            name: fluent-conf
      containers:
        - name: fluentd
          ports: 
          - containerPort: 24224
          image: grafana/fluent-plugin-loki:latest
          env:
          - name: LOKI_URL
            value: http://loki:3100
          volumeMounts:
          - name: config
            mountPath: /fluentd/etc/fluent.conf
            subPath: fluent.conf
        - name: p-one
          image: speedy1096/project-two:latest
          ports:
          - containerPort: 8080
          env:
          - name: DB_URL
            valueFrom: 
              secretKeyRef:
                name: chris-credentials
                key: url
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: chris-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chris-credentials
                key: password
          
